function stabilizer = example ()
    stabilizer = struct(...
    'config',1,...
    'no_of_vt',1...
    );
endfunction

function f = gog()
    f = struct(...
    'no_of_pilots',2,...
    'no_of_attendants',1...
    );
endfunction


function b = ccc()
    b = struct(...
    'kevin',3,...
    'mvin',4...
    );
endfunction
